---
title: "R Notebook"
output: html_notebook
---


```{r}

install.packages("mondate")
library(mondate)

library(stringr)

if (!require(remotes)) install.packages("remotes")
remotes::install_github("keithabailey/PRMTools")
library(PRMTools)

if (!require(dplyr)) install.packages("dplyr")
library(dplyr)

suppressPackageStartupMessages(if (!require(xts)) install.packages("xts"))
library(xts)
suppressPackageStartupMessages(if (!require(forecast)) install.packages("forecast") )
library(forecast)

if (!require(rlist)) install.packages("rlist")
library(rlist)


if (!require(Ecdat)) install.packages("Ecdat")
library(Ecdat)

if (!require(ggplot2)) install.packages("ggplot2")
library(ggplot2)

if (!require(Hmisc)) install.packages("Hmisc")
library(Hmisc)

if (!require(ISLR)) install.packages("ISLR")
library(ISLR)
```

```{r}
#Read files

sales_data_mod_a2020 <- read.csv("sales_data_mod_a2020.csv")
sales_data_mod_b2020 <- read.csv("sales_data_mod_b2020.csv")

head(sales_data_mod_b2020)
```

1a. Low Income After 2020 General Model

```{r}
sales_data_mod_b2020$month <- format(as.Date(sales_data_mod_b2020$zillow_month_day),"%m")
min_date <- as.Date(min(sales_data_mod_b2020$zillow_month_day))
sales_data_mod_b2020$month_number <- mondf(min_date, sales_data_mod_b2020$zillow_month_day)
list_columns <- colnames(sales_data_mod_b2020)
filter_columns = list_columns[grepl("^comp_ratio*|^zillow_sales_value_index|var_zip|^month", list_columns)]
filter_columns = filter_columns[!filter_columns %in% c("month_number","-zillow_sales_value_index_lag")]
df_lmb2020_low <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="low")%>%select(filter_columns)
lmb2020_low <- lm(zillow_sales_value_index ~ ., data=df_lmb2020_low)

print("Adjusted R square:")
summary(lmb2020_low)$adj.r.squared
print("FStatistic:")
summary(lmb2020_low)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_low)$coefficients)%>%filter(.[[4]] <0.05))
print("Largest coefficients:")
head(data.frame(summary(lmb2020_low)$coefficients)%>%filter(.[[4]] <0.05)%>% arrange(desc(abs(Estimate))),20)
sel_columns_lmb2020_low <- row.names(data.frame(summary(lmb2020_low)$coefficients)%>%filter(.[[4]] <0.05))

#list_sig_zips <- str_sub(sel_columns_lmb2020_low[grepl("var_zip", sel_columns_lmb2020_low)], start=8)



```

```{r}
df_lmb2020_low_opt <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="low")%>%select(c(sel_columns_lmb2020_low[!grepl("var_zip|^month|*Intercept*",sel_columns_lmb2020_low)],var_zip,month,zillow_sales_value_index,zillow_month_day))

lmb2020_low_opt <- lm(zillow_sales_value_index ~ .-zillow_month_day, data=df_lmb2020_low_opt)

print("Adjusted R square:")
summary(lmb2020_low_opt)$adj.r.squared
print("FStatistic:")
summary(lmb2020_low_opt)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_low_opt)$coefficients))
print("Largest coefficients:")
data.frame(summary(lmb2020_low_opt)$coefficients)%>% arrange(desc(abs(Estimate)))
print("Complaint coefficients:")
data.frame(summary(lmb2020_low_opt)$coefficients)[sel_columns_lmb2020_low[grepl("comp_ratio|Intercept",sel_columns_lmb2020_low)],]%>% arrange(desc(abs(Estimate)))

df_lmb2020_low_opt$prediction <- predict(lmb2020_low_opt, newdata=df_lmb2020_low_opt)

ggplot(data = df_lmb2020_low_opt,aes(x = as.Date(zillow_month_day))) + 
  stat_summary(aes(y = prediction, colour = "Predicted Index"),geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = prediction),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "red") +
  stat_summary(aes(y=zillow_sales_value_index, colour = "Actual Index"), geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = zillow_sales_value_index),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "blue") +
  scale_colour_manual("", 
                      breaks = c("Predicted Index", "Actual Index"),
                      values = c("red", "blue")) +
  xlab("Date")+
  ylab("Sales Zillow Home Value Index")+
  ggtitle("2010-2019 Zillow Home Value Time Series \n Low income areas - Actual vs Predicted")


```
2a. Medium Income After 2020 General Model

```{r}
sales_data_mod_b2020$month <- format(as.Date(sales_data_mod_b2020$zillow_month_day),"%m")
min_date <- as.Date(min(sales_data_mod_b2020$zillow_month_day))
sales_data_mod_b2020$month_number <- mondf(min_date, sales_data_mod_b2020$zillow_month_day)
list_columns <- colnames(sales_data_mod_b2020)
filter_columns = list_columns[grepl("^comp_ratio*|^zillow_sales_value_index|var_zip|^month", list_columns)]
filter_columns = filter_columns[!filter_columns %in% c("month_number","-zillow_sales_value_index_lag")]
df_lmb2020_medium <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="medium")%>%select(filter_columns)
lmb2020_medium <- lm(zillow_sales_value_index ~ ., data=df_lmb2020_medium)

print("Adjusted R square:")
summary(lmb2020_medium)$adj.r.squared
print("FStatistic:")
summary(lmb2020_medium)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_medium)$coefficients)%>%filter(.[[4]] <0.05))
print("Largest coefficients:")
head(data.frame(summary(lmb2020_medium)$coefficients)%>%filter(.[[4]] <0.05)%>% arrange(desc(abs(Estimate))),20)
sel_columns_lmb2020_medium <- row.names(data.frame(summary(lmb2020_medium)$coefficients)%>%filter(.[[4]] <0.05))

```

```{r}
df_lmb2020_medium_opt <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="medium")%>%select(c(sel_columns_lmb2020_medium[!grepl("var_zip|^month|*Intercept*",sel_columns_lmb2020_medium)],var_zip,month,zillow_sales_value_index,zillow_month_day))

lmb2020_medium_opt <- lm(zillow_sales_value_index ~ .-zillow_month_day, data=df_lmb2020_medium_opt)

print("Adjusted R square:")
summary(lmb2020_medium_opt)$adj.r.squared
print("FStatistic:")
summary(lmb2020_medium_opt)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_medium_opt)$coefficients))
print("Largest coefficients:")
data.frame(summary(lmb2020_medium_opt)$coefficients)%>% arrange(desc(abs(Estimate)))
print("Complaint coefficients:")
data.frame(summary(lmb2020_medium_opt)$coefficients)[sel_columns_lmb2020_medium[grepl("comp_ratio|Intercept",sel_columns_lmb2020_medium)],]%>% arrange(desc(abs(Estimate)))

df_lmb2020_medium_opt$prediction <- predict(lmb2020_medium_opt, newdata=df_lmb2020_medium_opt)

ggplot(data = df_lmb2020_medium_opt,aes(x = as.Date(zillow_month_day))) + 
  stat_summary(aes(y = prediction, colour = "Predicted Index"),geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = prediction),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "red") +
  stat_summary(aes(y=zillow_sales_value_index, colour = "Actual Index"), geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = zillow_sales_value_index),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "blue") +
  scale_colour_manual("", 
                      breaks = c("Predicted Index", "Actual Index"),
                      values = c("red", "blue")) +
  xlab("Date")+
  ylab("Sales Zillow Home Value Index")+
  ggtitle("2010-2019 Zillow Home Value Time Series \n Medium income areas - Actual vs Predicted")

```
3a. High Income After 2020 General Model

```{r}
sales_data_mod_b2020$month <- format(as.Date(sales_data_mod_b2020$zillow_month_day),"%m")
min_date <- as.Date(min(sales_data_mod_b2020$zillow_month_day))
sales_data_mod_b2020$month_number <- mondf(min_date, sales_data_mod_b2020$zillow_month_day)
list_columns <- colnames(sales_data_mod_b2020)
filter_columns = list_columns[grepl("^comp_ratio*|^zillow_sales_value_index|var_zip|^month", list_columns)]
filter_columns = filter_columns[!filter_columns %in% c("month_number","-zillow_sales_value_index_lag")]
df_lmb2020_high <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="high")%>%select(filter_columns)
lmb2020_high <- lm(zillow_sales_value_index ~ ., data=df_lmb2020_high)

print("Adjusted R square:")
summary(lmb2020_high)$adj.r.squared
print("FStatistic:")
summary(lmb2020_high)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_high)$coefficients)%>%filter(.[[4]] <0.05))
print("Largest coefficients:")
head(data.frame(summary(lmb2020_high)$coefficients)%>%filter(.[[4]] <0.05)%>% arrange(desc(abs(Estimate))),20)
sel_columns_lmb2020_high <- row.names(data.frame(summary(lmb2020_high)$coefficients)%>%filter(.[[4]] <0.05))

```

```{r}
df_lmb2020_high_opt <- sales_data_mod_b2020%>%filter(outlier==0)%>%filter(income_group=="high")%>%select(c(sel_columns_lmb2020_high[!grepl("var_zip|^month|*Intercept*",sel_columns_lmb2020_high)],var_zip,month,zillow_sales_value_index,zillow_month_day))

lmb2020_high_opt <- lm(zillow_sales_value_index ~ .-zillow_month_day, data=df_lmb2020_high_opt)

print("Adjusted R square:")
summary(lmb2020_high_opt)$adj.r.squared
print("FStatistic:")
summary(lmb2020_high_opt)$fstatistic

print("Number of significant variables:")
nrow(data.frame(summary(lmb2020_high_opt)$coefficients))
print("Largest coefficients:")
data.frame(summary(lmb2020_high_opt)$coefficients)%>% arrange(desc(abs(Estimate)))
print("Complaint coefficients:")
data.frame(summary(lmb2020_high_opt)$coefficients)[sel_columns_lmb2020_high[grepl("comp_ratio|Intercept",sel_columns_lmb2020_high)],]%>% arrange(desc(abs(Estimate)))

df_lmb2020_high_opt$prediction <- predict(lmb2020_high_opt, newdata=df_lmb2020_high_opt)

ggplot(data = df_lmb2020_high_opt,aes(x = as.Date(zillow_month_day))) + 
  stat_summary(aes(y = prediction, colour = "Predicted Index"),geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = prediction),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "red") +
  stat_summary(aes(y=zillow_sales_value_index, colour = "Actual Index"), geom = "line", fun = "mean", size= 1) +
  stat_summary(aes(y = zillow_sales_value_index),geom = "ribbon", fun.data = "mean_cl_normal", alpha = 0.1,fill = "blue") +
  scale_colour_manual("", 
                      breaks = c("Predicted Index", "Actual Index"),
                      values = c("red", "blue")) +
  xlab("Date")+
  ylab("Sales Zillow Home Value Index")+
  ggtitle("2010-2019 Zillow Home Value Time Series \n High income areas - Actual vs Predicted")

```

